import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import MuiXLicense from "@/lib/license/MuiXLicense";
import '@mantine/core/styles.css';

const zapfino = localFont({
  src: "../../public/fonts/Zapfino.ttf",
  variable: "--font-zapfino",
})
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const modelsignature = localFont({
  src:"../../public/fonts/Modelistasignature-ownAV.otf",
  variable:'--font-modelsignature'
})
const theseasons = localFont({
  src:[
    {
      path:"../../public/fonts/Fontspring-DEMO-theseasons-reg.otf",
    },
    {
      path:"../../public/fonts/Fontspring-DEMO-theseasons-bd.otf",
      weight:"bold"
    },
    {
      path:"../../public/fonts/Fontspring-DEMO-theseasons-bdit.otf",
      weight:"bold",
      style:"italic"
    },
    {
      path:"../../public/fonts/Fontspring-DEMO-theseasons-lt.otf",
      weight:"300"
    },{
      path:"../../public/fonts/Fontspring-DEMO-theseasons-ltit.otf",
      weight:"300",
      style:"italic"
    }
  ],
  variable:'--font-theseasons'
})
const bevietnam = localFont({
  src:[
    {
      path:"../../public/fonts/BeVietnamPro-Regular.ttf",
    },
    {
      path:"../../public/fonts/BeVietnamPro-Italic.ttf",
      style:"italic"
    },
    {
      path:"../../public/fonts/BeVietnamPro-Bold.ttf",
      weight:"bold"
    },
    {
      path:"../../public/fonts/BeVietnamPro-BoldItalic.ttf",
      weight:"bold",
      style:"italic"
    },
    {
      path:"../../public/fonts/BeVietnamPro-Thin.ttf",
      weight:"300"
    },
    {
      path:"../../public/fonts/BeVietnamPro-ThinItalic.ttf",
      weight:"300",
      style:"italic"
    }
  ],
  variable:'--font-bevietnam'
})
export const metadata: Metadata = {
  title: "EK-Wedding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-mantine-color-scheme="light">
      <head>
        <ColorSchemeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${modelsignature.variable} ${theseasons.variable} ${bevietnam.variable} ${zapfino.variable} antialiased`}
        cz-shortcut-listen="true"
      >
        <MantineProvider>

        {children}
        </MantineProvider>
        <MuiXLicense />
      </body>
    </html>
  );
}
